version: '3.3'

services:
  backend:
    build:
      context: ..
      dockerfile: Docker/Django/Dockerfile
    image: aeye_web_back:1.0
    container_name: aeye_web_back
    ports:
      - "8000:8000"
    volumes:
      - /Django:/app
    command: python3.6 manage.py runserver 0.0.0.0:8000
